#!/bin/bash
#$ -V
#$ -S /bin/bash
#$ -N LUMPY_merge
#$ -cwd
#$ -o /u/flashscratch/h/hjzhou/4-24-18Lumpy_merge.$JOB_ID.out
#$ -j y
#$ -m bea
#$ -l h_data=33G,h_rt=24:00:00
. /u/local/Modules/default/init/modules.sh
module load python/2.7
cd $SCRATCH/bipolar_lumpy/

python ~/lumpy-sv/scripts/l_merge.py -i Lumpy_master_sorted_1.vcf > Lumpy_master_merged_33G.vcf

/u/project/zarlab/jhsul/bin/bam_to_fastq/bam_to_fastq_3
