#!/bin/bash
#$ -V
#$ -S /bin/bash
#$ -N breakseq
#$ -cwd
#$ -o /u/home/l/lukezhan/joblogs
#$ -j y
#$ -m a
#$ -M zhanglucasjifeng@gmail.com
#$ -l h_data=10G,h_rt=20:00:00
. /u/home/l/lukezhan/SVPipeline/inputs.config 
. /u/local/Modules/default/init/modules.sh
module load python/2.7
input=$input_single 
outdir=/u/scratch/l/lukezhan/breakseqout/testing
bwa=/u/local/apps/bwa/current/bwa
samtools=/u/local/apps/samtools/0.1.19/gcc-4.4.7/samtools
bplib=/u/home/l/lukezhan/SVPipeline/Breakseq/bplib.hg38.gff
reference=$ref_genome
# Needs to provide reference genome
./breakseq2.sh ${input} ${outdir} ${reference} ${bwa} ${samtools} ${bplib}
