#!/bin/bash
#$ -V
#$ -S /bin/bash
#$ -N Manta
#$ -cwd
#$ -o /u/home/l/lukezhan/joblogs
#$ -j y
#$ -m a
#$ -M zhanglucasjifeng@gmail.com
#$ -l h_data=20G,h_rt=10:00:00

. /u/local/Modules/default/init/modules.sh
module load python/2.7.13
. /u/home/l/lukezhan/SVPipeline/inputs.config

python /u/home/l/lukezhan/manta-1.5.1.centos6_x86_64/bin/configManta.py --bam=$input_single --referenceFasta=$ref_genome --runDir=/u/scratch/l/lukezhan/mantaout/$JOB_ID 

python /u/scratch/l/lukezhan/mantaout/$JOB_ID/runWorkflow.py -m local 

 
