#!/bin/bash
#$ -V
#$ -S /bin/bash
#$ -N SVdisc100k
#$ -cwd
#$ -o /u/flashscratch/h/hjzhou/6-10-18SVDiscovery_100k.$JOB_ID.out 
#$ -j y  
#$ -m bea 
#$ -l h_data=20G,h_rt=72:00:00,highp


# load needed hoffman2 modules
. /u/local/Modules/default/init/modules.sh
module load java
module load R
module load samtools/1.2

SCRIPT_DIR=$SCRATCH

# MD_DIR is the location of the preprocessed metadata files
MD_DIR="/u/flashscratch/h/hjzhou/bipolar_sv_large"

# SV_DIR is the installation directory for SVToolkit - it must be an exported environment variable.
# SV_TMPDIR is a directory for writing temp files, which may be large if you have a large data set.
export SV_DIR="/u/home/a/alden/svtoolkit"
SV_TMPDIR="/u/flashscratch/h/hjzhou/bipolar_sv_tmpdir"

# runDir is where all the output files go
runDir="${SCRIPT_DIR}/redo_discovery_out/deletions100k.svtoolkit2017April.mask"

# These executables must be on your path.
which java > /dev/null || exit 1
which Rscript > /dev/null || exit 1
which samtools > /dev/null || exit 1

# For SVAltAlign, you must use the version of bwa compatible with Genome STRiP.
export PATH=${SV_DIR}/bwa:${PATH}
export LD_LIBRARY_PATH=${SV_DIR}/bwa:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=/u/systems/UGE8.0.1vm/lib/lx-amd64/:$LD_LIBRARY_PATH

# May need to raise to 8g and change the jobNative parameter below

mx="-Xmx4g"
classpath="${SV_DIR}/lib/SVToolkit.jar:${SV_DIR}/lib/gatk/GenomeAnalysisTK.jar:${SV_DIR}/lib/gatk/Queue.jar"

# Create needed runDir
mkdir -p ${runDir} || exit 1
mkdir -p ${runDir}/logs || exit 1

# Display version information.
java ${mx} -cp ${classpath} -jar -Djava.io.tmpdir="${SV_TMPDIR}" ${SV_DIR}/lib/SVToolkit.jar

# Run cnvdeletion pipeline
java ${mx} -cp ${classpath} \
     org.broadinstitute.gatk.queue.QCommandLine \
     -S ${SV_DIR}/qscript/SVDiscovery.q \
     -S ${SV_DIR}/qscript/SVQScript.q \
     -cp ${classpath} \
     -gatk ${SV_DIR}/lib/gatk/GenomeAnalysisTK.jar \
     -configFile ${SV_DIR}/conf/genstrip_parameters.txt \
     -R /u/home/a/alden/eeskin2/bipolar_sv/svtoolkit/reference/Homo_sapiens_assembly19.fasta \
     -I /u/home/h/hjzhou/batch_redo449.list \
     -genomeMaskFile /u/home/a/alden/eeskin2/bipolar_sv/svtoolkit/reference/Homo_sapiens_assembly19.svmask.fasta \
     -P select.validateReadPairs:false \
     -tempDir $SV_TMPDIR \
     -md ${MD_DIR}/batch1.0/metadata \
     -md ${MD_DIR}/batch1.1/metadata \
     -md ${MD_DIR}/batch1.2/metadata \
     -md ${MD_DIR}/batch1.3/metadata \
     -md ${MD_DIR}/batch1.4/metadata \
     -md ${MD_DIR}/batch2.0/metadata \
     -md ${MD_DIR}/batch2.1/metadata \
     -md ${MD_DIR}/batch2.2/metadata \
     -md ${MD_DIR}/batch2.3/metadata \
     -md ${MD_DIR}/batch2.4/metadata \
     -runDirectory $runDir \
     -jobLogDir $runDir/logs \
     -jobRunner "Drmaa" \
     -gatkJobRunner "Drmaa" \
     -jobNative "-V -l h_data=8G,h_rt=72:00:00,highp -m a" \
     -O ${runDir}/deletions100k.svtoolkit2017April.mask.svdiscovery.dels.100k.vcf \
     -minimumSize 100 \
     -maximumSize 100000 \
     -windowSize 10000000 \
     -windowPadding 3000 \
     -run \
     || exit 1
