#!/bin/bash
#$ -V
#$ -S /bin/bash
#$ -N delly
#$ -cwd
#$ -o /u/home/l/lukezhan/joblogs
#$ -j y
#$ -m a
#$ -M zhanglucasjifeng@gmail.com
#$ -l h_data=10G,h_rt=20:00:00

. /u/home/l/lukezhan/SVPipeline/inputs.config
input=$input_single
outdir=/u/scratch/l/lukezhan/dellyout
reference=$ref_genome
echo $input
echo $reference
# Needs to provide reference genome
bash delly.sh ${input} ${outdir} ${reference}
