#!/bin/bash
#$ -V
#$ -S /bin/bash
#$ -N CNVnator
#$ -cwd
#$ -o /u/home/l/lukezhan/joblogs
#$ -j y
#$ -m a
#$ -M zhanglucasjifeng@gmail.com
#$ -l h_data=15G,h_rt=20:00:00

. /u/home/l/lukezhan/SVPipeline/inputs.config
# requires ROOT
. /u/local/Modules/default/init/modules.sh
module load cern_root

# specify the variables
used_bamfile=$input_single
binsize=500
name=`echo $used_bamfile | sed -e 's/\/.*\///g' | sed 's/.dedup.realigned.recal.bam//g'`
CNVnatorPrefix=/u/home/l/lukezhan/CNVnator_v0.4.1/src
work_dir=$SCRATCH/CNVnator_large/$name
rootfile=$work_dir/${name}.root
hg19=$ref_genome

# make directories
mkdir -p $SCRATCH/CNVnator_large/
mkdir -p $work_dir
mkdir -p $work_dir/hist/

# Run CNVnator. $hg19/human.hg19.genome is the genome size file, which comes with all the chromosome fasta files. 
$CNVnatorPrefix/cnvnator -root $rootfile -unique -tree $used_bamfile
$CNVnatorPrefix/cnvnator -root $rootfile -genome $hg19 -his $binsize -d $hg19
$CNVnatorPrefix/cnvnator -root $rootfile -stat $binsize
$CNVnatorPrefix/cnvnator -root $rootfile -partition $binsize
$CNVnatorPrefix/cnvnator -root $rootfile -call $binsize > $SCRATCH/CNVnator_large/${name}.calls.txt


# You may want to delete the root file after the job is done
rm $rootfile

#Converting CNVnator data to VCF
. /u/home/l/lukezhan/Structural_Variants_pipeline/CNVnator/scripts/cnvnator2VCF.pl -prefix study1 -reference hg19 ${work_dir}.calls.txt $hg19

